name: Push Docker Image to ACR

on:
  workflow_dispatch:

permissions:
  id-token: write  

jobs:
  dockerhub-to-acr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Pull image from Docker Hub
        run: |
          docker pull node:18-alpine

      - name: Tag Docker image
        run: |
          docker tag node:18-alpine ${{ secrets.ACR_NAME }}.azurecr.io/my-node-app:latest

      - name: Push to ACR
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/my-node-app:latest
